services:
  sisgetask_backend:
    container_name: sisgetask_backend
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./sisgetask_backend:/sisgetask_backend
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:16-alpine
    volumes:
      - db_sisgetask_backend:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env
    ports:
      - "5432:5432"

volumes:
  db_sisgetask_backend: