# Generated by Django 5.2 on 2025-04-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('a iniciar', 'A iniciar'), ('em andamento', 'Em andamento'), ('finalizada', 'Finalizada')], default='a iniciar', max_length=20),
        ),
    ]
