# Generated by Django 5.2 on 2025-04-24 02:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('a iniciar', 'A iniciar'), ('em andamento', 'Em andamento'), ('finalizada', 'Finalizada')], default='a iniciar', max_length=20)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['start_date'],
            },
        ),
    ]
